### ISSUE TITLE
maxDate not working

### ISSUE THREAD

**Issue by hamx0r** [tazsingh/will_pickdate#3]
Using this code, can get the will_pickdate picker to show up, but it is not constrained by maxDate.  Both the picker allow me to pick later dates and the text that ends up into #entry_1 always matches the picker selection, even if it's later than maxDate.

```
 <script type="text/javascript">
  $(function(){
      $('#entry_1').will_pickdate({ timePicker: true, 
                                    format: 'j F Y @ h:iA', 
                                    degbug: true,
                                    inputOutputFormat: 'm-d-Y H:i:s',
                                    maxDate: {
                                        date: '11-13-2011',
                                        format: 'mdY'
                                    }
      });
  });
</script>
```

**Comment by astjohn** [comment]
There's a lot I don't like right now about the current implementation.  I'm not sure the "format" option is working properly.  In addition, I can't get it to work properly unless BOTH maxDate and minDate are specified.  I'll see what I can do.

**Comment by SimeonC** [comment]
The fix is for setting only one is relatively simple (if you haven't already found it :P), change line 582 to `if(!(cs || ce)) return false;` - or not and - ie only return false if BOTH are not set.

Not sure about the format - I'm using `{date: '2012-05-12', format: 'Y-m-d'}` and this works fine for me.

Nice plugin BTW, much better than the others I was using.

**Comment by tazsingh** [comment]
@SimeonC Thanks! Can you send me that in a pull request?
